# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='assitance_income',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='other_income',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='total_income',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='work_income',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='assistance_case_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_address_one',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_address_two',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_zip',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='total_adult_income',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='total_adult_income_assistance',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='total_adult_income_other',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='total_adult_income_wages',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='total_child_income',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='assitance_income',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='child',
            name='total_income',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='work_income',
            field=models.IntegerField(blank=True),
        ),
    ]
