# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_apply', '0002_auto_20160208_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='other_income',
            field=models.IntegerField(blank=True),
        ),
    ]
